### ISSUE TITLE
onPermissionsDenied method is not calling

### ISSUE THREAD

**Issue by nAkhmedov** [googlesamples/easypermissions#126]
When i deny all permissions with checking "Never ask option", i couldn't do anything then. What do you advice? Thanks in advance

**Comment by Heri88** [comment]
Did you find a solution to this?

**Comment by nAkhmedov** [comment]
I am using compile 'pub.devrel:easypermissions:0.4.0' version. Firstly, When i allow permission 'onRequestPermissionsResult' is calling but 'onPermissionsGranted' not. Secondly, i deny the permission with checked 'Never ask' option, then nothing i can do. The only option is that allow permission via App-> Settings

**Comment by samtstern** [comment]
@nAkhmedov if you deny the permission with "Never ask again" then that's the correct behavior, the user would have to grant the permission by going to app settings.

That's why we have `AppSettingsDialog` which you can learn more about in the "Required Permissions" section of the README:
https://github.com/googlesamples/easypermissions#required-permissions
