### ISSUE TITLE
Not working on Service

### ISSUE THREAD

**Issue by elsennov** [googlesamples/easypermissions#15]
Hi, how can i requestPermissions inside the Service? Since the code will throw an exception if it is accessed from outside of activity or fragment.
Thanks :)

**Comment by farhan-arbisoft** [comment]
No you can't. You can go into the source code for that.
It must need activity of fragment for that.

Ideally you should not call it from service because it needs the dialog to ask permission from user. You can call it at service or app starting time.

**Comment by samtstern** [comment]
@elsennov this is a limitation of the Android M permissions system.  Because you need to show UI to the user, permissions can only be requested from an Activity or Fragment context.

You can check which permissions you have from a service, but you will need at least one Activity in your app for the user interaction to grant the permissions.

I am going to close this issue as it is not something I can fix in the library.
