### ISSUE TITLE
READ_EXTERNAL_STORAGE permission permanently denied even though it hasn't been asked before?

### ISSUE THREAD

**Issue by Daltron** [googlesamples/easypermissions#158]
Even after I delete the app and reinstall, the else statement is always called. Why is this permission always being detected as denied when it has never been asked for? Any help would be appreciated! 😄 

```java
if (EasyPermissions.hasPermissions(getContext(), perms)) {
            Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
            intent.setType("image/*");
            intent = Intent.createChooser(intent, "Select Picture");
            if (intent.resolveActivity(getActivity().getPackageManager()) != null) {
                startActivityForResult(intent, REQUEST_PICK_IMAGE);
            }
 } else if (!EasyPermissions.permissionPermanentlyDenied(this, Manifest.permission.READ_EXTERNAL_STORAGE)) {
            // Do not have permissions, request them now
            EasyPermissions.requestPermissions(
                    this,
                    getString(R.string.external_storage_rationale),
                    READ_EXTERNAL_STORAGE_PERMISSION,
                    perms);
} else {
            new AppSettingsDialog.Builder(this, getString(R.string.external_storage_rationale)).build().show();
}
```

I am also including this in my manifest
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by samtstern** [comment]
@Daltron I understand how this can be confusing, but this is the expected behavior.  Take a look at the implementation of `permissionPermanentlyDenied`:

https://github.com/googlesamples/easypermissions/blob/25302f5672a851444d74909ac7472db3dffae860/easypermissions/src/main/java/pub/devrel/easypermissions/helper/PermissionHelper.java#L95

So basically `"should not show rationale" == "permission permanently denied"`.  However if you have never asked for the permission, then should show rationale will be false.

This is why `permissionPermanentlyDenied` should only be used in a permission denial callback, and should not be used before the permission has been requested.

**Comment by Daltron** [comment]
@samtstern Thanks for the quick and detailed response. That is very confusing for somebody who doesn't dig into the source code. It would be great if there was a way to do what I thought it did before requesting the permission. iOS's permission system has a huge step up on Android's in my opinion.

Anyways, thanks! 👍
