### ISSUE TITLE
how to using it when the class not activity or fragment?

### ISSUE THREAD

**Issue by ling9400** [googlesamples/easypermissions#46]
i am getting the devicedId in just an util class,how should i do?

**Comment by samtstern** [comment]
@ling9400 the short answer is "you can't" since in order to display the permission prompt we must have an Activity context to show the UI. This is not only a requirement of this library, but a requirement of the Android system.

You can **receive** the result of the EasyPermissions request in a non-Activity/Fragment class, but the request must be initiated from an Activity or Fragment.
