### ISSUE TITLE
有中文版说明吗？

### ISSUE THREAD

**Issue by zhaoxiuyu** [googlesamples/easypermissions#47]
有中文版说明吗？

**Comment by samtstern** [comment]
@zhaoxiuyu sorry I don't speak any Chinese ... the best I can tell from google translate is that you're asking for a Chinese version?

I don't believe there is anything stopping you from using this library with chinese strings, if you want chinese documentation that would be better as a fork since I would not feel comfortable maintaining that.

**Comment by zaijie1213** [comment]
看不懂英文写什么代码

**Comment by lby1992** [comment]
@samtstern I can help you to provide the manual in Chinese

**Comment by samtstern** [comment]
@lby1992 I really appreciate the offer but I'd have no way to know if the manual was actually correct!  If you do publish a manual in Chinese somewhere else (maybe a blog?) I would be happy to link to it.

**Comment by lby1992** [comment]
Hi, @samtstern I haven't make a Chinese manual yet, if you wanna provide it for Chinese user, I would be glad to do it.
