### ISSUE TITLE
Method.isAnnotationPresent method removed from the API 24 SDK

### ISSUE THREAD

**Issue by rogyinapp** [googlesamples/easypermissions#63]
Solved problem by modifying code locally in **EasyPermissions.java** class

  if (method.isAnnotationPresent(AfterPermissionGranted.class)) {
**to**
   if (method.getAnnotation(AfterPermissionGranted.class) != null) {

**Comment by samtstern** [comment]
@rogyinapp could you explain the issue you're having?  `Method#isAnnotationPresent` comes from the [AnnotatedElement](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/AnnotatedElement.html) class which is part of Java, not the Android SDK.  As far as I can tell it has not changed at all between Java 7 and Java 8, so it's not deprecated and it's definitely not "removed" in Android 24 (or 25).

**Comment by rogyinapp** [comment]
Please check below links
https://code.google.com/p/android/issues/detail?id=222709
https://developer.android.com/sdk/api_diff/24/changes/java.lang.Class.html

**Comment by SUPERCILEX** [comment]
@samtstern the reason this isn't relevant to us and the code still compiles is because we use `Method#isAnnotationPresent` implemented in `AbstractMethod#isAnnotationPresent` from the interface `AnnotatedElement#isAnnotationPresent`. @rogyinapp Your diff show that `Class#isAnnotationPresent` was removed, not `AnnotatedElement#isAnnotationPresent`. In addition, it looks like that diff is wrong for some reason: here is [that method in api 23](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-23/blob/master/java/lang/Class.java#L1227) and it's [still there in api 24](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-24/blob/master/java/lang/Class.java#L2369).

**Comment by SUPERCILEX** [comment]
I did some more research and the only difference I can see between api levels 23 and 24 are that `AnnotatedElement#isAnnotationPresent` now includes a default implementation and the implementation for `isAnnotationPresent` have moved from `Method` to `AbstractMethod`. @rogyinapp are you experiencing a compile error? I'm confused because to `Method`, only the implementation details have changed and nothing else. Same goes `Class`, so what's happening?

**Comment by samtstern** [comment]
I think @SUPERCILEX is correct here, I have not seen any issues or heard any other reports so I am going to close this.
